version: "3"

services: 
    tdd_db:
        container_name: tdd_db_mysql
        image: mysql

        ports:
            - 3303:3306
        volumes:
            - "${PWD}/db:/docker-entrypoint-initdb.d"
        environment: 
            MYSQL_USER: root
            MYSQL_ROOT_PASSWORD: mysql
            # MYSQL_PASSWORD: mysql
            MYSQL_DATABASE: tdd_db

    go_test_env:
        container_name: go_tdd
        build:
            context: .
            dockerfile: Dockerfile
        
        environment: 
            RETRY_COUNT: 20
        command: 
            - go test -v /go/tdd_db_test.go